# Generated by Django 5.1.7 on 2025-03-23 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('discription', models.TextField()),
                ('status', models.CharField(choices=[('PAN', 'panding'), ('COM', 'complete'), ('REJ', 'rejected')])),
                ('data_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
