# Generated by Django 5.1.7 on 2025-03-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_task_manager_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_manager',
            old_name='data_time',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='discription',
            field=models.TextField(default=1313),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='name',
            field=models.CharField(default=1313),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='status',
            field=models.CharField(choices=[('PAN', 'pending'), ('COM', 'complete'), ('REJ', 'rejected')], default='Panding'),
        ),
    ]
